### PR TITLE
add new monster sprite

### PR DESCRIPTION
**Pull request by tristansokol**
Paint.net doesn't really gel with my mac lifestyle so I used an online tool [http://www.piskelapp.com/](http://www.piskelapp.com/) to do the sprite editing. I guessed some info about the sprite size, so it might look kind of funny. I got the sprite asset from [http://www.dumbmanex.com/bynd_freestuff.html](http://www.dumbmanex.com/bynd_freestuff.html). Also I've never played Joust.

### CODE REVIEW

**Comment by ajgriesemer** [comment]
Hi tristansokol, 
Thank you for your pull request. We here at GameDev are interested in keeping this project as open as possible. However, we also need to guarantee the authenticity of the experience our product provides. As such we can't accept your contribution until you full understand the product.
Here is a link to play Joust online: https://archive.org/details/arcade_joust. Report back here when you've made it to at least level 3 and we'll further consider your pull request.

Sincerely,
ajgriesemer
Community Outreach
GameDev

**Comment by tristansokol** [comment]
Thanks ajgriesemer, I can always appreciate a repo that wants the best from their contributors. After some playtesting I was able to make it to level 4 with a top score of 17500. Know a little more about the game's characters might make this pull request a little strange looking, but I would love to see what it looks like. 

Also, do you know if it is possible to change the sprite size? 
screen shot 2016-04-28 at 2 50 31 pm

**Comment by ajgriesemer** [comment]
We're happy to inform you that we've accepted your contribution to the GameDev project. For the team members who did not receive the snapchat here's a screenshot of our new art
image. I think it's a big improvement.

You can change the size of the sprite in two ways. You can modify how each pixel is a scaled to a "game unit" by clicking the sprite sheet in the project navigator and changing the "Pixels per unit" in the inspector. It's set to 60 right now. You can also change the amount the sprite is scaled when it's shown in the scene by editing the game object. Right now that's scaled by 1x.

We've also separated the flying bird and the rider into seperate sprites so we can use the rider color to indicate who is in control of each player and the color of the bird to indicate what team they are on. That could all change pretty easily.

**Comment by tristansokol** [comment]
Project navigator? Still waiting on that getting started guide.

**Comment by ajgriesemer** [comment]
Participation in this repo is going to assume a baseline level of understanding of working in Unity. There are some good tutorials online for getting started.

I did pieces of these:
https://unity3d.com/learn/tutorials/topics/2d-game-creation
https://www.youtube.com/playlist?list=PLlHjNcdoyw6UK30xrTUhjM-usQOOE5jhN

Lyndon did this one:
https://unity3d.com/learn/tutorials/projects/2d-roguelike-tutorial

Since we both did different tutorials we had similar understandings of the most basic parts of Unity, but we each became familiar with different parts of the slightly more complicated parts of Unity. So if you find another relevant tutorial you could increase the overall understanding of our development community.

**Pull request merged**
