### PR TITLE
add new cave background, and possibly upgrade to unity 5.3

### PR DESCRIPTION
**Pull request by tristansokol**
I added a new asset for the cave background, replacing the barren black background. I also might have messed up other settings though, so somebody should test this out before merging.

### CODE REVIEW

**Comment by ajgriesemer** [comment]
Can this be a branch?

**Comment by tristansokol** [comment]
Are you asking because you never want to merge it? Because if you don't like the background we should just not merge it.

**Comment by ajgriesemer** [comment]
It's the messed up settings that make me nervous.

**Comment by tristansokol** [comment]
That is sort of the point of this pull request, so that other members of the dev team can test it out, see if anything broke (possibly upgrade their Unity to the latest version) and merge. Alternatively you can just merge the things that you to change and I can stop tracking those configuration files.

**Comment by ajgriesemer** [comment]
That makes sense. I'll take a look at the changes this weekend. Hopefully Lyndon and I can work on this after climbing on Sunday.

**Comment by lsapoz** [comment]
Congratulations!

Our QA team has verified that nothing in your pull request results in game breaking functionality. Thank you for your contribution!

**Pull request merged**
